[package]
name = "rust_web_server"
version = "0.1.0"
authors = ["Grant Greer <grantgreerdev@gmail.com>"]
edition = "2021"


[dependencies]
serde_json = "1.0"
serde = "1.0"
log = "0.4"
env_logger = "0.9"
